export { createFigurestead } from "./create-matrix-plot.js";
export { validateContract, FiguresteadConfigError, SCHEMA_VERSION, LEGACY_SCHEMA_VERSION } from "./schema.js";
export { CORE_REGISTRY, CORE_RENDERERS } from "./core-renderers.js";
export { createRendererRegistry, defineRenderer, RENDERER_API_VERSION } from "./registry.js";
export { deriveFigureLayout } from "./figure-layout.js";
export { linearScale, timeScale, bandScale, parseTime, timeTicks, formatTimeTick } from "./scales.js";
export { drawRule, drawBand, drawBar, drawInterval, drawCell } from "./primitives.js";
export { rendererConformance, assertRendererConformance } from "./renderer-test-kit.js";
export { prepareLine, lineSegmentState } from "./renderers/line.js";
export { SCIENTIFIC_POSE, applyEvidencePose, applyScientificPose } from "./presentation.js";
export { APPLICATION_PROFILE_VERSION, APPLICATION_PROFILES, applyApplicationProfile, resolveApplicationProfile } from "./application-profiles.js";
export { APPEARANCE_VERSION, composeAppearance } from "./appearance.js";
export { SERIES_STYLE_VERSION, GLYPH_CYCLE, LINE_STYLE_CYCLE, HATCH_CYCLE, collectSeriesKeys, resolveSeriesStyles, styleForSeries } from "./series-style.js";
export { TERMINAL_SCENE_VERSION, canonicalTerminalEvidence, compileFigureModel, compileTerminalScene, evidenceFingerprint, terminalEvidence } from "./terminal-scene.js";
export { RESOLVED_SCENE_VERSION, RESOLVED_RENDERERS, isResolvedRenderer, resolveSceneFrame, resolveTerminalScene, resolvedTerminalGeometry } from "./resolved-scene.js";
export { COMPOSED_SCENE_VERSION, auditComposition, composeResolvedScene } from "./composition.js";
export { MOTION_PLAN_VERSION, ALLOWED_MOTION_CHANNELS, TERMINAL_MOTION_STATE, assertTerminalMotionIdentity, compileMotionPlan, markMotionState, strategyForRenderer } from "./motion-plan.js";
export { exportFigureSvg, resolvedSceneToSvg, sceneToSvg } from "./svg-export.js";
export { EXPORT_MANIFEST_VERSION, FIGURESTEAD_PACKAGE_VERSION, canvasToPngBlob, exportFigureArtifacts, stableStringify } from "./export-bundle.js";
export { MOTION_RECIPE_VERSION, MOTION_RECIPES, applyMotionRecipe, resolveMotionRecipe } from "./motion-recipes.js";
export { THEME_CATALOG_VERSION, auditThemeCatalog, catalogThemePack, mergeThemePacks } from "./theme-catalog.js";
export { prepareScatter } from "./renderers/scatter.js";
export { prepareStrip } from "./renderers/strip-summary.js";
export { AnimationClock } from "./clock.js";
export { THEME_PACK_VERSION, PALETTE_PACK_VERSION, applyTheme, contrastAudit, contrastRatio, loadThemePack, normalizeThemePackLenient, resolveTheme, resolvePalette, themeForProfile, validateAuthoredThemePack, validateThemePack, validatePalettePack } from "./theme-pack.js";
export { RENDER_LAYER_ORDER, partitionPanelMarks, plotClipRect, renderLayerForMark, withCanvasPlotClip } from "./render-layers.js";
export { validateEvidenceCoverage } from "./evidence-coverage.js";
export { colorContrast, hexToOklab, hexToOklch, oklabDistance, oklchToHex, resolveContrastColor } from "./color-space.js";
export { PAPER_FLOORS, PAPER_PROFILE_VERSION, PAPER_SURFACE, auditPaperTheme, resolvePaperTheme, themeResolutionForProfile } from "./paper-profile.js";
export { PAPER_SIZE_PRESETS, auditPhysicalTypography, resolveExportSize } from "./physical-export.js";
